Repository miurahr/aqtinstall, pull requests merged in 2023-11, with the labels that each got.

#684 Add `ignore_hash` option in `settings.ini`
  aqt/archives.py
  aqt/helper.py
  aqt/installer.py
  aqt/metadata.py
  aqt/settings.ini
  docs/configuration.rst
Labels: enhancement

#728 docs: update authors and fix syntax
  docs/authors.rst
  docs/configuration.rst
  docs/getting_started.rst
  docs/previous_changes.rst
Labels: documents

#732 Fix issue #731
  aqt/metadata.py
Labels: bug

#733 docs: update link urls in CoC
  docs/CODE_OF_CONDUCT.rst
Labels: documents
